services:
  - type: web
    name: clara-certificados
    env: docker
    plan: free
    region: oregon
    envVars:
      - key: ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_URL_DIRECT
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
    healthCheckPath: /healthz
