"""initial schema

Revision ID: 45750400216c
Revises: 
Create Date: 2026-06-16 14:44:48.991072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45750400216c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ASESOR', 'REVISOR', name='role_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.Enum('LOGIN_SUCCESS', 'LOGIN_FAILED', 'LOGOUT', 'USER_CREATED', 'USER_ROLE_CHANGED', 'USER_DISABLED', 'USER_ENABLED', 'CERT_CREATED', 'CERT_UPDATED', 'CERT_SUBMITTED', 'CERT_VIEWED', 'CERT_APPROVED', 'CERT_REJECTED', 'CERT_PDF_GENERATED', 'CERT_EMAIL_SENT', 'CERT_EMAIL_FAILED', name='audit_action_enum'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_table('certificate_requests',
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', name='status_enum'), nullable=False),
    sa.Column('asesor_id', sa.Uuid(), nullable=False),
    sa.Column('revisor_id', sa.Uuid(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_comment', sa.Text(), nullable=True),
    sa.Column('cliente_nombre_completo', sa.String(length=255), nullable=False),
    sa.Column('cliente_tipo_documento', sa.String(length=20), nullable=False),
    sa.Column('cliente_numero_documento', sa.String(length=30), nullable=False),
    sa.Column('cliente_telefono', sa.String(length=30), nullable=False),
    sa.Column('cliente_email', sa.String(length=255), nullable=False),
    sa.Column('cliente_direccion', sa.String(length=255), nullable=True),
    sa.Column('cliente_ciudad', sa.String(length=100), nullable=True),
    sa.Column('cliente_parentesco', sa.String(length=100), nullable=False),
    sa.Column('fallecido_nombre_completo', sa.String(length=255), nullable=False),
    sa.Column('fallecido_tipo_documento', sa.String(length=20), nullable=False),
    sa.Column('fallecido_numero_documento', sa.String(length=30), nullable=False),
    sa.Column('fallecido_fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('fallecido_fecha_fallecimiento', sa.Date(), nullable=False),
    sa.Column('fallecido_lugar_fallecimiento', sa.String(length=255), nullable=True),
    sa.Column('fallecido_causa_fallecimiento', sa.String(length=255), nullable=True),
    sa.Column('fallecido_numero_acta_defuncion', sa.String(length=50), nullable=True),
    sa.Column('plan_o_poliza', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asesor_id'], ['users.id'], name=op.f('fk_certificate_requests_asesor_id_users')),
    sa.ForeignKeyConstraint(['revisor_id'], ['users.id'], name=op.f('fk_certificate_requests_revisor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certificate_requests'))
    )
    op.create_index(op.f('ix_certificate_requests_asesor_id'), 'certificate_requests', ['asesor_id'], unique=False)
    op.create_index(op.f('ix_certificate_requests_cliente_numero_documento'), 'certificate_requests', ['cliente_numero_documento'], unique=False)
    op.create_index(op.f('ix_certificate_requests_fallecido_numero_documento'), 'certificate_requests', ['fallecido_numero_documento'], unique=False)
    op.create_index(op.f('ix_certificate_requests_status'), 'certificate_requests', ['status'], unique=False)
    op.create_table('sessions',
    sa.Column('session_token_hash', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('csrf_secret', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_session_token_hash'), 'sessions', ['session_token_hash'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_session_token_hash'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_certificate_requests_status'), table_name='certificate_requests')
    op.drop_index(op.f('ix_certificate_requests_fallecido_numero_documento'), table_name='certificate_requests')
    op.drop_index(op.f('ix_certificate_requests_cliente_numero_documento'), table_name='certificate_requests')
    op.drop_index(op.f('ix_certificate_requests_asesor_id'), table_name='certificate_requests')
    op.drop_table('certificate_requests')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
    # Postgres ENUM types are created independently of the tables that use
    # them, so op.drop_table above does not drop them — must do so explicitly
    # for downgrade to be fully reversible.
    sa.Enum(name='status_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='audit_action_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='role_enum').drop(op.get_bind(), checkfirst=True)
